#!/usr/bin/env python
"""Github teams discovery.

This script identifies teams associated with HMPPS repositories and stores the
results in the Service Catalogue.

Required environment variables
------------------------------

Github (Credentials for Discovery app that has access to the repositories)
- GITHUB_APP_ID: Github App ID
- GITHUB_APP_INSTALLATION_ID: Github App Installation ID
- GITHUB_APP_PRIVATE_KEY: Github App Private Key

Service Catalogue
- SERVICE_CATALOGUE_API_ENDPOINT: Service Catalogue API endpoint
- SERVICE_CATALOGUE_API_KEY: Service Catalogue API key

- SLACK_BOT_TOKEN: Slack Bot Token

Optional environment variables
- SLACK_NOTIFY_CHANNEL: Slack channel for notifications
- SLACK_ALERT_CHANNEL: Slack channel for alerts
- LOG_LEVEL: Log level (default: INFO)
"""

# hmpps
from hmpps import GithubSession, ServiceCatalogue, Slack
from hmpps.services.job_log_handling import log_info, job

# local
from processes import github_teams


class Services:
  def __init__(self):
    self.sc = ServiceCatalogue()
    self.gh = GithubSession()
    self.slack = Slack()


def summarize_processed_teams(processed_teams):
  item_type = 'Github Teams'
  summary = (
    f'Github Teams discovery completed OK\n{item_type.upper()} SUMMARY\n'
    f'{"=" * (len(item_type) + 8)}\n'
  )
  team_attributes = {
    'terraform_managed': 'teams are terraform managed',
    'team_added': 'team(s) added',
    'team_updated': 'team(s) updated',
    'team_deleted': 'team(s) deleted',
    'team_references_removed': 'team(s) removed from all components',
    'team_failure': 'team(s) that encountered errors',
  }
  for attr, desc in team_attributes.items():
    filtered_items = [item for item in processed_teams if item[1].get(attr)]
    summary += f'- {len(filtered_items)} {desc}\n'
    # if filtered_items:
    #   for item in filtered_items:
    #     summary += f'  {item[0]}\n'
    #   summary += '\n'
  summary += (
    '\n_(generated by <https://github.com/ministryofjustice/'
    'hmpps-github-discovery|hmpps-github-discovery>)_'
  )
  return summary


def main():
  job.name = 'hmpps-github-teams-discovery'  # type: ignore[assignment]
  services = Services()
  slack = services.slack
  sc = services.sc

  log_info('Processing teams...')
  processed_teams = github_teams.process_github_teams(services)
  log_info('Finished processing teams.')

  summary = summarize_processed_teams(processed_teams)
  slack.notify(summary)
  log_info(summary)

  if job.error_messages:
    sc.update_scheduled_job('Errors')
    log_info('Github teams discovery job completed  with errors.')
  else:
    sc.update_scheduled_job('Succeeded')
    log_info('Github teams discovery job completed successfully.')


if __name__ == '__main__':
  main()
