#!/usr/bin/env python
"""Github security - a separate script that interrogates github API for security info
   about hmpps components and stores the results in the service catalogue

Required environment variables
------------------------------

Github (Credentials for Discovery app that has access to the repositories)
- GITHUB_APP_ID: Github App ID
- GITHUB_APP_INSTALLATION_ID: Github App Installation ID
- GITHUB_APP_PRIVATE_KEY: Github App Private Key

Service Catalogue
- SERVICE_CATALOGUE_API_ENDPOINT: Service Catalogue API endpoint
- SERVICE_CATALOGUE_API_KEY: Service

- SLACK_BOT_TOKEN: Slack Bot Token

Optional environment variables
- SLACK_NOTIFY_CHANNEL: Slack channel for notifications
- SLACK_ALERT_CHANNEL: Slack channel for alerts
- LOG_LEVEL: Log level (default: INFO)
"""

# hmpps
from hmpps import ServiceCatalogue, GithubSession, Slack
from hmpps.services.job_log_handling import (
  log_error,
  log_info,
  job,
)

# local
from processes import components

# Set maximum number of concurrent threads to run, try to avoid secondary github
# api limits.
max_threads = 10


class Services:
  def __init__(self):
    self.slack = Slack()
    self.sc = ServiceCatalogue()
    self.gh = GithubSession()


# def create_summary(services, processed_components):
def create_summary(services, processed_components):
  # Summarize the items based on the attributes

  def summarize_processed_components(items, item_type, attributes):
    summary = (
      f'Github Security Discovery completed OK\n{item_type.upper()} SUMMARY\n'
      f'{"=" * (len(item_type) + 8)}\n'
    )
    summary += f'{len(items)} {item_type.lower()}(s) processed\n'
    for attr, desc in attributes.items():
      filtered_items = [item for item in items if item[1].get(attr)]
      summary += f'- {len(filtered_items)} {desc}\n'
      # if filtered_items and 'update' not in desc and 'add' not in desc:
      #   for item in filtered_items:
      #     summary += f'  {item[0]}\n'
      #   summary += '\n'
    summary += (
      '\n_(generated by <https://github.com/ministryofjustice/hmpps-github-discovery|'
      'hmpps-github-discovery>)_'
    )
    return summary

  component_attributes = {
    'repos_with_vulnerabilities': 'repositories with vulnerabilities',
  }

  summary = 'Github Security Discovery completed OK\n'
  summary += summarize_processed_components(
    processed_components, 'component', component_attributes
  )

  services.slack.notify(summary)
  log_info(summary)


def main():
  #### Create resources ####
  job.name = 'hmpps-github-discovery-security'

  services = Services()
  slack = services.slack
  sc = services.sc
  gh = services.gh

  # Send some alerts if there are service issues
  if not sc.connection_ok:
    slack.alert('*Github Discovery failed*: Unable to connect to the Service Catalogue')
    raise SystemExit()

  if not gh.org:
    slack.alert('*Github Discovery (security)*: Unable to connect to Github')
    log_error('*Github Discovery (security)*: Unable to connect to Github')
    sc.update_scheduled_job('Failed')
    raise SystemExit()

  # Since we're running this on a schedule, this is of no further use to us
  # Start health endpoint.
  # health_server = HealthServer()
  # httpHealth = threading.Thread(target=health_server.start, daemon=True)
  # httpHealth.start()

  log_info('Batch processing components')
  processed_components = components.batch_process_sc_components(
    services,
    max_threads,
    module='processes.security',
    function='process_sc_component_security',
  )

  create_summary(services, processed_components)

  if job.error_messages:
    sc.update_scheduled_job('Errors')
    log_info('Github security discovery job completed with errors.')
  else:
    sc.update_scheduled_job('Succeeded')
    log_info('Github security discovery job completed successfully.')


if __name__ == '__main__':
  main()
