---
image:
  repository: ghcr.io/ministryofjustice/hmpps-github-discovery
  tag: latest
  
generic-prometheus-alerts:
  targetApplication: hmpps-github-discovery

discoveryCronJob:
  namespace_secrets:
    hmpps-github-discovery:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
      GITHUB_APP_ID: "GITHUB_APP_ID"
      GITHUB_APP_INSTALLATION_ID: "GITHUB_APP_INSTALLATION_ID"
      GITHUB_APP_PRIVATE_KEY: "GITHUB_APP_PRIVATE_KEY"
      CIRCLECI_TOKEN: "CIRCLECI_TOKEN"
      CIRCLECI_API_ENDPOINT: "CIRCLECI_API_ENDPOINT"
      SLACK_BOT_TOKEN: "SLACK_BOT_TOKEN"
      

