{{- if .Values.discoveryCronJob.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-teams-discovery-script
data:
  github_teams_discovery.py: |-
    {{ .Files.Get "github_teams_discovery.py" | indent 4 }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-teams-discovery
spec:
  schedule: "20 */6 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: github-teams-discovery
              image: ghcr.io/ministryofjustice/hmpps-github-discovery
              command: ["python", "-u", "/app/github_teams_discovery.py"]
              env:
                - name: PATH
                  value: "/home/appuser/.local:/usr/local/bin:$PATH"
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
      {{- include "discoveryCronJob.envs" .Values | nindent 14 }}
          restartPolicy: Never
{{- end }}
