{{- if .Values.workflowsCronJob.enabled -}}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-github-discovery-workflows
spec:
  schedule: "{{ .Values.workflowsCronJob.cron.github_discovery_workflows }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0 # Set to 0 to prevent retries after job failure - API Rate limit is 15000 per hour so reties will not solve the issue
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: github-discovery
              image: "{{ .Values.image.repository }}:{{ .Values.version }}"
              command: ["uv", "run", "python", "-u", "/app/github_workflows_discovery.py"]
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
      {{- include "github_discovery.envs" .Values | nindent 14 }}
          restartPolicy: Never
{{- end }}
