name: Cloud Platform Deploy
description: Deploy to Cloud Platform using Helm

inputs:
  environment:
    description: The environment to deploy to (dev/staging/preprod/prod)
    required: true
  version:
    description: The version of the service to deploy
    required: true
  api:
    description: The KUBE_ENV_API
    required: true
  cert:
    description: The KUBE_CERT
    required: true
  cluster:
    description: The KUBE_CLUSTER
    required: true
  namespace:
    description: The KUBE_NAMESPACE
    required: true
  token:
    description: The KUBE_TOKEN
    required: true
  k8s_deployment_name:
    description: "Kubernetes deployment name"
    default: 'PROJECT_NAME'
    required: false
  changelog_git_paths:
    default: ""
    description: When set it will limit the file changes shown in the changelog to the specified paths only. This is useful for multi-project builds where otherwise it will show all changes from all projects.
    required: false
  show_changelog:
    description: Whether the changelog should be sent by slack
    required: false
  helm_additional_args: 
    description: any additional helm arguments
    required: false
    default: ""
  helm_timeout: 
    description: helm timeout period
    required: false
    default: 5m
  helm_dir: 
    description: location of helm configuration
    required: false
    default: helm_deploy
  helm_allowlist_groups:
    description: values for location of allowlist groups file
    required: false
  helm_allowlist_version:
    description: setting for version of allowlist file
    required: false
  slack_notify_channel:
    description: slack channel to notify
    required: false
  slack_alert_channel:
    description: slack channel to alert
    required: false

outputs:
  deployment_changelog:
    description: "The changelog for the deployment" 
    value: ${{ steps.version_history.outputs.deployment_changelog }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Authenticate
      uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-auth@v2 # WORKFLOW_VERSION
      with:
        api: ${{ inputs.api }}
        cert: ${{ inputs.cert }}
        cluster: ${{ inputs.cluster }}
        namespace: ${{ inputs.namespace }}
        token: ${{ inputs.token }}

    - name: Deploy
      shell: bash
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install helm
        yq -i ".appVersion = \"${{ inputs.version }}\"" "${{ inputs.helm_dir }}/${{ github.event.repository.name }}/Chart.yaml"
        helm dependency update "${{ inputs.helm_dir }}/${{ github.event.repository.name }}"
        exec helm upgrade '${{ github.event.repository.name }}' '${{ inputs.helm_dir }}/${{ github.event.repository.name }}' \
          --atomic \
          --history-max 10 \
          --force \
          --install \
          --reset-values \
          --set 'generic-service.image.tag=${{ inputs.version }}' \
          --set 'version=${{ inputs.version }}' \
          --set 'global.environment=${{ inputs.environment }}' \
          --set 'discoveryCronJob.env.SLACK_NOTIFY_CHANNEL=${{ inputs.slack_notify_channel }}' \
          --set 'discoveryCronJob.env.SLACK_ALERT_CHANNEL=${{ inputs.slack_alert_channel }}' \
          --timeout ${{ inputs.helm_timeout }} \
          --values 'helm_deploy/values-${{ inputs.environment }}.yaml' \
          ${{ inputs.helm_additional_args }} \
          ${{ steps.check-ip-allowlists.outputs.ALLOWLIST_GROUPS }} \
          ${{ steps.check-ip-allowlists-version.outputs.ALLOWLIST_VERSION }} \
          --wait
