---
# Per environment values which override defaults in hmpps-github-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

github-discovery:
  env:
    LOG_LEVEL: debug
    SC_FILTER: "SC_FILTER"

discoveryCronJob:
  enabled: false
  # cron:
  #   github_discovery: "45 */6 * * *"
  #   github_discovery_full: "45 2 * * *"

teamsCronJob:
  enabled: false
  # cron:
  #   github_teams_discovery: "20 2 * * *"

securityCronJob:
  enabled: false
  # cron:
  #   github_discovery_security: "30 06 * * 1-5"

workflowsCronJob:
  enabled: true
  cron:
    github_discovery_workflows: "40 9 * * 4"
