---
# Per environment values which override defaults in hmpps-github-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  enabled: true
  env:
    LOG_LEVEL: debug
    SC_FILTER: "SC_FILTER"

cron:
#   github_teams_discovery: "20 2 * * *"
#   github_discovery: "45 */6 * * *"
#   github_discovery_full: "45 2 * * *"
  github_discovery_security: "30 10 * * *"