---
# Per environment values which override defaults in hmpps-github-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

github-discovery:
  env:
    LOG_LEVEL: debug
    SC_FILTER: "SC_FILTER"

discoveryCronJob:
  enabled: true
  cron:
    github_discovery: "25 15 * * *"
    github_discovery_full: "45 2 * * *"

teamsCronJob:
  enabled: true
  cron:
    github_teams_discovery: "45 15 * * *"

securityCronJob:
  enabled: false
  # cron:
  #   github_discovery_security: "30 06 * * 1-5"

workflowsCronJob:
  enabled: false
  # cron:
  #   github_discovery_workflows: "40 9 * * 4"
