---
# Per environment values which override defaults in hmpps-github-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

github_discovery:
  env:
    LOG_LEVEL: "DEBUG"
    SC_FILTER: "SC_FILTER"

  namespace_secrets:
    hmpps-envoy-https-proxy-env:
      HTTP_PROXY: "HTTP_PROXY"
      HTTPS_PROXY: "HTTPS_PROXY"
      NO_PROXY: "NO_PROXY"
      http_proxy: "HTTP_PROXY"
      https_proxy: "HTTPS_PROXY"
      no_proxy: "NO_PROXY"

discoveryCronJob:
  enabled: true
  env:
    LOG_LEVEL: "INFO"
    SC_FILTER: "&filters[name][$contains]=hmpps-book"
  cron:
    github_discovery: "45 12 * * 1-5"
    github_discovery_full: "50 9 * * 0"

teamsCronJob:
  enabled: true
  cron:
    github_teams_discovery: "35 10 * * 0"

securityCronJob:
  enabled: true
  cron:
    github_discovery_security: "00 07 * * 0"

workflowsCronJob:
  enabled: true
  cron:
    github_discovery_workflows: "40 7 * * 0"

dependenciesCronJob:
  enabled: false
  # cron:
  #   github_discovery_dependencies_latest: "15 07 * * *"

deploymentAnalyticsCronJob:
  enabled: false
  # cron:
  #   github_deployment_analytics: "45 22 * * tue"
  # env:
  #   LOG_LEVEL: "DEBUG"
  #   FOLDER_PATH: "analytics-validation/deployments"
  #   UPLOAD: true
  # namespace_secrets:
  #   azure-sharepoint-service-principal:
  #     SP_CLIENT_ID: SP_CLIENT_ID
  #     SP_CLIENT_SECRET: SP_CLIENT_SECRET
  #     AZ_TENANT_ID: AZ_TENANT_ID
