name: Check for duplicate envs in Service Catalogue

on:
  workflow_dispatch:
  schedule:
    - cron: "15 7,11,15 * * MON-FRI" # Every weekday at 13:45 UTC
    
jobs:
  duplicate-environments:
    name: Run duplicate environment check
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    permissions:
      contents: read
    outputs:
      results: ${{ steps.check.outputs.results }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: '3.13'

      - name: Run duplicate environment check
        id: check
        run: |
          rm -f uv.lock
          uv run python utilities/check_duplicate_environments.py
        env:
          SERVICE_CATALOGUE_API_ENDPOINT: ${{ vars.SERVICE_CATALOGUE_API_ENDPOINT }}
          SERVICE_CATALOGUE_API_KEY: ${{ secrets.SERVICE_CATALOGUE_API_KEY }}
          SLACK_ALERTS_CHANNEL: ${{ vars.PROD_SLACK_ALERT_CHANNEL}}

      - id: send-slack 
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        if: steps.check.outputs.results == 'YES' 
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload-file-path: ./slack-message.json
