name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      environment: 
        description: Environment
        required: true 
        type: string
      app_version:
        description: App version
        required: true 
        type: string
      k8s_deployment_name:
        description: Kubernetes deployment name
        default: "PROJECT_NAME"
        required: false
        type: string
      changelog_git_paths:
        description: Changelog git paths
        required: false
        default: ""
        type: string
      show_changelog:
        description: Show changelog
        default: true
        required: false
        type: boolean
      slack_notification:
        description: Slack notification
        default: "false"
        required: false
        type: string
      helm_additional_args:
        description: Helm additional args
        default: "--set 'discoveryCronJob.env.SLACK_NOTIFY_CHANNEL=${{ vars.PROD_SLACK_NOTIFY_CHANNEL }}'  --set 'discoveryCronJob.env.SLACK_ALERT_CHANNEL=${{ vars.PROD_SLACK_ALERT_CHANNEL }}'"
        required: false
        type: string
      helm_timeout:
        description: Helm timeout
        default: "5m"
        required: false
        type: string
      helm_dir:
        description: Helm dir
        default: "helm_deploy"
        required: false
        type: string
      slack_alert_channel:
        description: Slack alert channel
        default: ""
        required: false
        type: string
      slack_notify_channel:
        description: Slack notify channel
        default: ""
        required: false
        type: string

permissions:
  contents: read

jobs:
  deploy_env:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-kubectl@v4
        id: install
        with:
          version: latest

      - uses: ministryofjustice/hmpps-github-actions/.github/actions/build-test-and-deploy/cloud-platform-deploy@v2 # WORKFLOW_VERSION
        id: deploy
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.app_version }}
          api: https://${{ secrets.KUBE_CLUSTER }}
          cert: ${{ secrets.KUBE_CERT }}
          cluster: ${{ secrets.KUBE_CLUSTER }}
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          token: ${{ secrets.KUBE_TOKEN }}
          k8s_deployment_name: ${{ inputs.k8s_deployment_name }}
          changelog_git_paths: ${{ inputs.changelog_git_paths }}
          show_changelog: ${{ inputs.show_changelog }}
          helm_additional_args: ${{ inputs.helm_additional_args }}
          helm_timeout: ${{ inputs.helm_timeout }}
          helm_dir: ${{ inputs.helm_dir }}
          helm_allowlist_groups: ${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_YAML }}
          helm_allowlist_version: ${{ vars.HMPPS_IP_ALLOWLIST_GROUPS_VERSION }}
