name: Pipeline

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true      

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      push: true
    secrets: inherit
  
  deploy_to_dev:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      environment: development
      version: ${{ needs.build.outputs.version }}
    secrets: inherit

  deploy_to_prod:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    needs:
      - build
      - deploy_to_dev # wait for the deploy_to_dev job to complete
    with:
      environment: production
      version: ${{ needs.build.outputs.version }}
    secrets: inherit
